
addpath(genpath('../src/'));

fprintf( 'converting:\n' )

ONSASFiles = {'./staticVonMisesTruss/onsasExample_staticVonMisesTruss.m', ...
              './uniformCurvatureCantilever/onsasExample_uniformCurvatureCantilever.m' , ...
              './uniaxialExtension/onsasExample_uniaxialExtension.m' ...
              } ;

MDFiles    = { '~/.julia/dev/ONSAS_docs/docs/src/staticVonMisesTruss.md' ...
              ,'~/.julia/dev/ONSAS_docs/docs/src/cantileverBeam.md' ...
              ,'~/.julia/dev/ONSAS_docs/docs/src/uniaxialExtension.md' ...
              } ;

for i=1:length(ONSASFiles)
  fprintf([ '  - ' ONSASFiles{i} '\n' ])
  m2md( ONSASFiles{i} , MDFiles{i},1)
end
