# This is the ONSAS.m documentation continuous integration config file
#
name: docs
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: extract markdown from example scripts
        uses: matlab-actions/run-command@v1
        with:
          command: ./docs/src/bringONSASmFilesToONSASdocs.m
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.7
      - name: Install julia dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter")'
      - name: Build and deploy
        env:
          url: https://onsas.github.io/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
