# This is a basic workflow to help you get started with Actions
name: tests
on: [push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@v1.1
        with:
          tests: test
