# This is the ONSAS.m coode testing continuous integration config file
#
name: tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: run mechanical-work tests
        uses: joergbrech/moxunit-action@v1.2.0
        with:
          tests: test/runTestProblems_moxunit_disp.m
          src: .
          with_coverage: true
          cover_xml_file: coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
