# This is a basic workflow to help you get started with Actions
name: tests
on: [push, pull_request]
jobs:
  tests-disp:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: run mechanical-work tests
        uses: joergbrech/moxunit-action@v1.1
        with:
          src: examples/staticVonMisesTruss examples/linearPlaneStrainExample examples/uniformCurvatureCantilever examples/frameLinearAnalysis examples/uniaxialExtension src src/elements src/vtk src/mesh
          tests: ./test/runTestProblems_moxunit_disp.m
          cover_json_file: coverage.json
      - uses: actions/upload-artifact@v1
        with:
          name: coverage_json
          path: coverage.json

      #     cover_xml_file: coverage.xml
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: coverage_file
      #     path: coverage.xml
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: ./coverage.xml
  #tests-heat:
  #  runs-on: [ubuntu-latest]
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: joergbrech/moxunit-action@v1.1
  #      with:
  #        src: examples/heatRobiAndNeum examples/heatAnalytic src
  #        tests: ./test/runTestProblems_moxunit_heat.m
