# This is the ONSAS.m coode testing continuous integration config file
#
name: tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: run mechanical-work tests
        uses: joergbrech/moxunit-action@v1.1
        with:
          src: examples/staticVonMisesTruss examples/frameLinearAnalysis examples/springMass examples/linearPlaneStrain examples/uniformCurvatureCantilever examples/uniaxialExtension examples/nonlinearPendulum examples/beamTrussJoint examples/cantileverSelfWeight examples/linearAerodynamics examples/simpleWindTurbine src src/elements src/vtk src/materials src/mesh
          tests: ./test/runTestProblems_moxunit_disp.m
